locale: fr

backend:
  name: github
  site_domain: beta.gouv.fr
  repo: betagouv/beta.gouv.fr
  commit_messages:
    create: Création de {{slug}} dans {{collection}} !
    update: Mise à jour de {{slug}} dans {{collection}}
    delete: Suppression de {{slug}} dans {{collection}}
    uploadMedia: Nouvelle image {{path}}
    deleteMedia: Suppression de l'image {{path}}
  squash_merges: true

# Permet d'expérimenter en local
# cf. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
# local_backend: true

media_folder: "img/netlifycms"

display_url: https://beta.gouv.fr

# La preview n'est pas utile juste pour modifier des auteurs
show_preview_links: false

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "."

# Editorial workflow: validate changes through pull requests
publish_mode: editorial_workflow

date_field_defaults: &date_field_defaults
  widget: datetime
  dateFormat: YYYY-MM-DD
  timeFormat: false
  default: null

collections:
  - name: incubators
    label: Incubateurs
    label_singular: Incubateur
    folder: "content/_incubators"
    create: true
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: Nom, name: title, widget: string }
      - { label: Responsable, name: owner, widget: string }
      - { label: Site, name: website, widget: string }
      - { label: Dépôts des produits, name: github, widget: string }
      - { label: Contact, name: contact, widget: string }
      - { label: Adresse, name: address, widget: string }
      - label: Redirections
        label_singular: Redirection
        name: redirect_from
        widget: list
        collapsed: false
        field: { label: Source, name: name, widget: string }
  - name: startups
    label: Produits
    label_singular: Produit
    folder: "content/_startups"
    create: true
    delete: false
    editor:
      preview: false
    fields:
      - label: Nom
        name: title
        widget: string
      - label: Objectif
        name: mission
        widget: string
      - label: Administration partenaire
        name: owner
        widget: string
      - label: "Incubateur"
        name: "incubator"
        widget: string
      - label: Status
        name: status
        widget: string
      - label: Lien vers le produit
        name: link
        widget: string
        required: false
      - label: Lien vers le code source
        name: repository
        widget: string
        required: false
      - label: Email de contat
        name: contact
        widget: string
        required: false
      - label: Statistiques d'usage publiques
        name: stats
        widget: boolean
        required: false
      - <<: *date_field_defaults
        label: "Date de début de l'investigation"
        name: start
      - <<: *date_field_defaults
        label: "Date du lancement du produit"
        name: product_launch_date
        required: false
      - <<: *date_field_defaults
        label: "Date du passage à un produit d'impact national majeur"
        name: national_scale_date
        required: false
      - <<: *date_field_defaults
        label: "Date de l'abandon"
        name: end
        required: false
      - label: Description
        name: body
        widget: text
  - name: "authors"
    identifier_field: fullname
    label: "Membres"
    label_singular: "Membre"
    description: "Les membres de la communauté beta.gouv.fr. Pour modifier une fiche, clique sur son nom ou recherche-la dans la barre de gauche. Pour ajouter un nouveau membre, direction \"Créer une entrée de type Membre\" !"
    folder: "content/_authors"
    create: true
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Nom complet"
        hint: "Format : Prénom Nom. Ton nom complet est utilisé pour le nom de ta fiche. Attention à ton orthographe !"
        name: "fullname"
        widget: "string"

      - label: "Rôle"
        hint: "Développeuse ? Intrapreneur ? Chargée de développement ? Coach ?"
        name: "role"
        widget: "string"

      - label: "Github"
        hint: "Ton nom d'utilisateur GitHub. Il te permet de rejoindre automatiquement l'organisation GitHub betagouv."
        name: "github"
        widget: "string"
        required: false

      - label: "Avatar"
        hint: "À remplir si tu veux mettre un avatar depuis un site externe. Tu peux aussi laisser vide et mettre une image dans le dossier /img/authors/. À défaut, on regardera si tu as une image sur ton profil Github. En dernier, la fiole beta.gouv.fr sera affichée sur la page communauté. Dans le doute : demande à ton marrain !"
        name: "avatar"
        widget: "string"
        required: false

      - label: "Lien externe"
        hint: "Lien vers une page perso externe."
        name: "link"
        widget: "string"
        required: false

      - label: 'Missions'
        label_singular: "Mission"
        hint: "Ton historique de missions avec nous dans l'ordre chronologique."
        name: 'missions'
        widget: 'list'
        fields:
          - label: "Statut"
            hint: "Quelle est ta relation professionnelle avec nous ?"
            name: "status"
            widget: "select"
            options:
              - { label: "Agent public", value: "admin" }
              - { label: "Indépendant", value: "independent" }
              - { label: "Société ou prestataire de services", value: "service" }

          - label: "Employeur"
            hint: "Si besoin de préciser : ton ministère d'origine, ta SSII, etc."
            name: "employer"
            widget: "string"
            required: false

          - label: "Date de début"
            hint: "Début de ton contrat ou de ton financement."
            name: "start"
            widget: "date"
            format: "YYYY-MM-DD"
            dateFormat: "LL"

          - label: "Date de fin"
            hint: "Fin de ton contrat ou de ton financement - tu pourras la modifier plus tard."
            name: "end"
            widget: "date"
            format: "YYYY-MM-DD"
            dateFormat: "LL"

      - label: "Startups"
        label_singular: "Startup"
        hint: "Plusieurs choix possibles. Si la startup n'apparait pas encore dans la liste, contacte un administrateur du site !"
        name: "startups"
        widget: "relation"
        multiple: true
        collection: "startups"
        valueField: "title"
        searchFields: ["title"]
        required: false

      - label: "Anciennes Startups"
        label_singular: "Ancienne Startup"
        hint: "Plusieurs choix possibles : sur quelles startups de la communauté tu as travaillé avant ?"
        name: "previously"
        widget: "relation"
        multiple: true
        collection: "startups"
        valueField: "title"
        searchFields: ["title"]
        required: false

      - label: "Description"
        hint: "Raconte-nous qui tu es dans une phrase percutante !"
        name: "body"
        widget: "text"
        required: false
